In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing Data Set and Data Preprocessing

In [2]:
data = pd.read_excel('datasets_847257_1445479_Patient_Info.xls')
risk=[]
for i in data.index:
    if data['Value of S4'][i]>=0 and data['Value of S4'][i]<=0.3:
        risk.append(1)
    elif data['Value of S4'][i]>0.3 and data['Value of S4'][i]<=0.5:
        risk.append(2)
    elif data['Value of S4'][i]>0.5 and data['Value of S4'][i]<=0.7:
        risk.append(3)
    elif data['Value of S4'][i]>0.6 and data['Value of S4'][i]<0.8:
        risk.append(4)
    elif data['Value of S4'][i]>=0.8 and data['Value of S4'][i]<1:
        risk.append(5)
data['Risk'] = risk
data = data.drop('Patient Info', axis=1)
data = data.rename(columns = {'Value of S4': 'Risk Factor'})
data

Risk Factor  Risk
0       0.654059     3
1       0.204378     1
2       0.801476     5
3       0.559345     3
4       0.691384     3
..           ...   ...
495     0.485189     2
496     0.392971     2
497     0.708396     4
498     0.653069     3
499     0.337441     2

[500 rows x 2 columns]

In [3]:
data.shape

(500, 2)

In [4]:
data.describe()

Risk Factor        Risk
count   500.000000  500.000000
mean      0.495200    2.676000
std       0.286392    1.481693
min       0.000017    1.000000
25%       0.233058    1.000000
50%       0.499825    2.500000
75%       0.738648    4.000000
max       0.998622    5.000000

# Splitting the data set into train and test set

In [5]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.4,random_state=200)

# Applying Random Forest on the Train Set

In [7]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 1000,min_samples_split=2,min_samples_leaf=5, max_features =0.000001)
model.fit(X_train, y_train)

RandomForestClassifier(max_features=1e-06, min_samples_leaf=5,
                       n_estimators=1000)

# Predicting the Test Set and Visualising the Accuracy

In [8]:
 y_pred = model.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.985

# Visualising the Confusion Matrix for each level

In [10]:
from sklearn.metrics import multilabel_confusion_matrix

In [11]:
mcm = multilabel_confusion_matrix(y_test, y_pred)
print(mcm)

[[[142   0]
  [  0  58]]

 [[161   0]
  [  2  37]]

 [[149   2]
  [  1  48]]

 [[184   1]
  [  0  15]]

 [[161   0]
  [  0  39]]]


# Classification Report

In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        58
           2       1.00      0.95      0.97        39
           3       0.96      0.98      0.97        49
           4       0.94      1.00      0.97        15
           5       1.00      1.00      1.00        39

    accuracy                           0.98       200
   macro avg       0.98      0.99      0.98       200
weighted avg       0.99      0.98      0.99       200



# Sensitivity of the model

In [13]:
sens = ((1)+(37/39)+(48/49)+(1)+(1))/5
print(sens)

0.9856619570905284


#  Sensitivity of the model

In [14]:
spec = ((1)+(1)+(149/151)+(184/185)+(1))/5
print(spec)

0.9962699122964024


# Predicting a single value depending on the Risk Factor

In [15]:
ar = model.predict([[0.7]])
print(ar)

[4]


In [16]:
if ar==[1]:
    print('Positive')
elif ar == [2]:
    print('High Risk')
elif ar == [3]:
    print('Moderate Risk')
elif ar == [4]:
    print('Low Risk')
elif ar == [5]:
    print('No risk')
else:
    print('Wrong Prediction')

Low Risk
